name: Discord Logs

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Make script executable
        run: chmod +x .github/scripts/discord-webhook.sh

      - name: Extract Data
        id: data
        run: |
          echo "MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_OUTPUT
          echo "AUTHOR=${{ github.event.head_commit.author.name }}" >> $GITHUB_OUTPUT
          echo "REPO=${{ github.repository }}" >> $GITHUB_OUTPUT
          echo "URL=${{ github.event.head_commit.url }}" >> $GITHUB_OUTPUT
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

          FILES=$(git diff --name-only HEAD^ HEAD | wc -l)

          FILE_LIST=$(git diff --name-only HEAD^ HEAD | awk '{print "• " $0}' | head -5)

          echo "FILES=$FILES" >> $GITHUB_OUTPUT

          {
            echo "FILE_LIST<<EOF"
            echo "$FILE_LIST"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Send Commit Log
        env:
          DISCORD_COMMIT_WEBHOOK: ${{ secrets.DISCORD_COMMIT_WEBHOOK }}
        run: |
          MESSAGE="${{ steps.data.outputs.MESSAGE }}"

          COLOR=5814783
          TYPE="📦 Commit"

          if [[ "$MESSAGE" == feat* ]]; then
            COLOR=5763719
            TYPE="✨ Feature"
          elif [[ "$MESSAGE" == fix* ]]; then
            COLOR=15548997
            TYPE="🐛 Fix"
          elif [[ "$MESSAGE" == refactor* ]]; then
            COLOR=16776960
            TYPE="♻️ Refactor"
          elif [[ "$MESSAGE" == docs* ]]; then
            COLOR=3447003
            TYPE="📝 Docs"
          elif [[ "$MESSAGE" == chore* ]]; then
            COLOR=9807270
            TYPE="🛠️ Chore"
          fi

          DESCRIPTION="$MESSAGE

          📌 Tipo: $TYPE
          👤 Autor: ${{ steps.data.outputs.AUTHOR }}
          🌿 Branch: ${{ steps.data.outputs.BRANCH }}

          📁 Arquivos:
          ${{ steps.data.outputs.FILES }} alterados

          📄 Alterações:
          ${{ steps.data.outputs.FILE_LIST }}

          📦 Repositório:
          ${{ steps.data.outputs.REPO }}"

          ./.github/scripts/discord-webhook.sh \
          "$DISCORD_COMMIT_WEBHOOK" \
          "DealFlowAI Logs" \
          "🚀 Novo Commit - DealFlowAI" \
          "$DESCRIPTION" \
          "$COLOR"